=== UWE-AI-GROUP/ipat/web/data/Ipat.xsd
<?xml version="1.0"  encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified"   >

<xs:element name="profile" type="profileType"/>
<xs:element name="kernel" type="kernelType"/>
<xs:element name="variable" type="variableType"/>        
<xs:element name="variableList" type="variableListType"/>
<xs:element name="kernelList" type="kernelListType"/> 
<xs:element name="globalscore" type="globalScoreType"/>
<xs:element name="interaction" type ="interactionType"/>  
<xs:element name="hint" type="hintType"/> 
    
    <xs:simpleType name="nameType">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    
    <xs:complexType name="globalScoreType">
        <xs:sequence>
            <xs:element name="value" type="xs:decimal"/>
            <xs:element name="ubound" type="xs:decimal"/>
            <xs:element name="lbound" type="xs:decimal"/>
        </xs:sequence>
    </xs:complexType>
        
    <xs:simpleType name="varType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="boolean"/>
            <xs:enumeration value="Boolean"/>
            <xs:enumeration value="ordinal"/>
            <xs:enumeration value="cardinal"/>
            <xs:enumeration value="permutation"/>
        </xs:restriction>
    </xs:simpleType>
    
<xs:complexType name="variableType">
    <xs:all>
        <xs:element name="name" type="nameType"/>
        <xs:element name="type" type="varType"/>
        <xs:element name="lbound" type="xs:decimal"/>
        <xs:element name="ubound" type="xs:decimal"/>
        <xs:element name="granularity" type="xs:string"/>
        <xs:element name="rateOfEvolution" type="xs:decimal"/>
        <xs:element name="value" type="xs:decimal"/>
        <xs:element name="default" type="xs:string"/>
        <xs:element name="unit" type="xs:string"/>
        <xs:element name="flag" type="xs:string"/>
    </xs:all>
</xs:complexType>


<xs:complexType name="kernelType">
    <xs:sequence>
            <xs:element name="name" type="nameType" />
            <xs:element name="variable" type= "variableType" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>


<xs:complexType name="kernelListType">
    <xs:sequence>
  <xs:element name="kernel" type="kernelType" minOccurs="1" maxOccurs="unbounded"/>
  </xs:sequence>
</xs:complexType>


<xs:complexType name="variableListType">
    <xs:sequence>
  <xs:element name = "variable" type="variableType" minOccurs="1" maxOccurs="unbounded"/>
  </xs:sequence>
</xs:complexType>



<xs:complexType name="profileType">
    <xs:sequence>
        <xs:element name="variable" type="variableType" minOccurs="0" maxOccurs="unbounded" />
        <xs:element name="kernel" type="kernelType" minOccurs="0" maxOccurs="unbounded" />
         <xs:element name="globalscore" type="globalScoreType"/>
     </xs:sequence>
</xs:complexType>

    
        
   <xs:simpleType name="displayType">
        <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="range"/>
            <xs:enumeration value="checkbox"/>
        </xs:restriction>
    </xs:simpleType>
        
  <xs:simpleType name="effectType">
        <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="setRateOfEvolutionEqualZero"/>
            <xs:enumeration value="moderateByValue"/>
            <xs:enumeration value="toggle"/>
            <xs:enumeration value="setNewValue"/>
        </xs:restriction>
    </xs:simpleType>        
            
            
 
            

    <xs:complexType  name="interactionType">
        <xs:sequence>
            <xs:element name="name" type="nameType" />  
            <xs:element name="displaytype" type="displayType" /> 
            <xs:element name="displayText" type="xs:string" />
            <xs:element name="range-min" type="xs:decimal" />
            <xs:element name="range-max" type="xs:decimal" />
            <xs:element name="default" type="xs:string" />
             <xs:element name="ProfileVariablesAffected" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
             <xs:element name="KernelAffected" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
              <xs:element name="KernelVariableAffected" type="xs:string" minOccurs="0" maxOccurs="unbounded"  />
             <xs:element name="Effect" type="effectType" /> 
        </xs:sequence>
    </xs:complexType>
 


<xs:complexType name="hintType">
    <xs:sequence>
         <xs:element name="interaction" type="interactionType" minOccurs="1" maxOccurs="unbounded"/>
  </xs:sequence>
</xs:complexType>



</xs:schema>

=== UWE-AI-GROUP/ipat/web/data/CSS Evolution/hints.xml
<?xml version="1.0"?><hint xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"xsi:noNamespaceSchemaLocation="../Ipat.xsd">    <interaction>        <name>            globalScore        </name>        <displaytype>            range        </displaytype>        <displayText>            Score        </displayText>        <range-min>            0        </range-min>        <range-max>            10        </range-max>        <default>            0        </default>        <ProfileVariablesAffected>            globalScore        </ProfileVariablesAffected>        <KernelAffected></KernelAffected>        <KernelVariableAffected></KernelVariableAffected>        <Effect>            setNewValue        </Effect>    </interaction>    <interaction>        <name>            FreezeBGColours        </name>        <displaytype>            checkbox        </displaytype>        <displayText>            Freeze Background        </displayText>        <range-min>0.0</range-min>        <range-max>1.0</range-max>        <default>            False        </default>        <ProfileVariablesAffected>            Page_bg_Red        </ProfileVariablesAffected>        <ProfileVariablesAffected>            Page_bg_Blue        </ProfileVariablesAffected>        <ProfileVariablesAffected>            Page_bg_Green        </ProfileVariablesAffected>        <Effect>            setRateOfEvolutionEqualZero        </Effect>    </interaction>    <interaction>        <name>            ChangeFontSize        </name>        <displaytype>            range        </displaytype>        <displayText>            Text Size        </displayText>        <range-min>            0        </range-min>        <range-max>            2        </range-max>        <default>            1        </default>        <KernelAffected>             h1        </KernelAffected>        <KernelAffected>             h2        </KernelAffected>        <KernelAffected>             p        </KernelAffected>        <KernelVariableAffected>            font-size        </KernelVariableAffected>        <Effect>            moderateByValue        </Effect>    </interaction>     <interaction>        <name>           ChangeFGContrast        </name>         <displaytype>            range        </displaytype>        <displayText>            Text Contrast        </displayText>        <range-min>            0        </range-min>        <range-max>            2        </range-max>        <default>            1        </default>        <KernelAffected>             h1        </KernelAffected>        <KernelAffected>             h2        </KernelAffected>        <KernelAffected>             p        </KernelAffected>        <KernelVariableAffected>            bold        </KernelVariableAffected>         <KernelVariableAffected>            italic        </KernelVariableAffected>        <Effect>            toggle        </Effect>    </interaction> </hint>

=== UWE-AI-GROUP/ipat/web/data/UML Evolution/hints.xml
<?xml version="1.0"?><hint xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"xsi:noNamespaceSchemaLocation="../../Ipat.xsd">    <interaction>        <name>            globalScore        </name>        <displaytype>            range        </displaytype>        <displayText>            Score        </displayText>        <range-min>            0        </range-min>        <range-max>            10        </range-max>        <default>            0        </default>        <KernelAffected>         </KernelAffected>        <KernelVariableAffected>                    </KernelVariableAffected>        <ProfileVariablesAffected>            globalScore        </ProfileVariablesAffected>        <Effect>            setNewValue        </Effect>    </interaction><!--rest of the interactions are for CSS evolution and need rethinking for the UML design applicationbut they do give the right format for  an interactin so rather than delete they are just  commented out for now            <interaction>        <name>            FreezeBGColours        </name>        <displaytype>            checkbox        </displaytype>        <displayText>            Freeze Background        </displayText>        <default>            False        </default>        <KernelAffected>         </KernelAffected>        <KernelVariableAffected>                    </KernelVariableAffected>        <ProfileVariablesAffected>            Page_bg_Red        </ProfileVariablesAffected>        <ProfileVariablesAffected>            Page_bg_Blue        </ProfileVariablesAffected>        <ProfileVariablesAffected>            Page_bg_Green        </ProfileVariablesAffected>        <Effect>            setRateOfEvolutionEqualZero        </Effect>    </interaction>    <interaction>        <name>            ChangeFontSize        </name>        <displaytype>            range        </displaytype>        <displayText>            Text Size        </displayText>        <range-min>            0        </range-min>        <range-max>            2        </range-max>        <default>            1        </default>        <KernelAffected>             h1        </KernelAffected>        <KernelAffected>             h2        </KernelAffected>        <KernelAffected>             p        </KernelAffected>        <KernelVariableAffected>            fontsize        </KernelVariableAffected>        <ProfileVariablesAffected>                    </ProfileVariablesAffected>        <Effect>            moderateByNewValue        </Effect>    </interaction>   --></hint>
